import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="fixed top-0 left-0 right-0 h-32 flex justify-between align-items">
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          <nav className="flex">
            <ul className="flex">
              <li>
                <a href="/">Hem</a>
              </li>
              <li>
                <a href="/about">Uppdrag</a>
              </li>
              <li>
                <a href="/about">Konsulter</a>
              </li>
              <li>
                <a href="/about">Om Oss</a>
              </li>
              <li>
                <a href="/about">Kontakta oss</a>
              </li>
            </ul>
          </nav>
          <nav className="flex">
            <ul className="flex">
              <li>
                <a href="/login">Logga in</a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="/register">Registrera</a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="/profile">Profil</a>
              </li>
            </ul>
          </nav>
        </header>
      

        {children}
        
        </body>
    </html>
  );
}
